### ISSUE TITLE
Hey

### ISSUE THREAD

**Issue by Bustinngg** [useragents/Snapchat-Snapscore-Botter#1]
Can you help me it wont let me do "pip install -r requirements.txt"
![image](https://user-images.githubusercontent.com/87212811/162598404-addcacb2-f999-48f1-a86a-218869b9e94e.png)

**Comment by MantisGalaxy** [comment]
Change your directory to where the file is located. You could've read the error message.

**Comment by useragents** [comment]
Use `cd (directory)`  in Command Prompt to move to a specific directory where the `requirements.txt` file is located.
For example, `cd C:\Users\MAX\...`
