### ISSUE TITLE
Python closing on start

### ISSUE THREAD

**Issue by MagzTVT** [useragents/Snapchat-Snapscore-Botter#12]
https://user-images.githubusercontent.com/92992555/164533873-2bc6900e-1638-428b-9efb-89f705ea216f.mp4

**Comment by Dom13377** [comment]
its a cli, run from cmd

**Comment by x198x** [comment]
you will have to install all modules in requirements by using 'pip install ' in cmd

**Comment by useragents** [comment]
Looks like you haven't installed the modules. Type the following into Command Prompt:
`pip install colorama`
`pip install keyboard`
`pip install PyAutoGUI`

**Comment by MagzTVT** [comment]
> its a cli tool, run from cmd

how. i installed those

pip install colorama
pip install keyboard
pip install PyAutoGUI
pip install requirements.txt

but it does the same
