### ISSUE TITLE
i press main.py and it shuts immediately not sure why.

### ISSUE THREAD

**Issue by oozi5C** [useragents/Snapchat-Snapscore-Botter#13]
![Screenshot (4)](https://user-images.githubusercontent.com/104264386/164912285-6a5fed73-5b4a-47f8-8d14-7b1d11dee8d8.png)
ive tried to get a screenshot of what it says and this is the closest i can get before it closes.

**Comment by useragents** [comment]
Please follow the usage:
2. Install [requirements.txt](https://github.com/useragents/Snapchat-Snapscore-Botter/blob/main/requirements.txt) by typing `pip install -r requirements.txt` in Command Prompt

**Comment by oozi5C** [comment]
> Please follow the usage:
> 2. Install [requirements.txt](https://github.com/useragents/Snapchat-Snapscore-Botter/blob/main/requirements.txt) by typing `pip install -r requirements.txt` in Command Prompt
i have already done this and it still says that
