### ISSUE TITLE
ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'

### ISSUE THREAD

**Issue by althanisa** [useragents/Snapchat-Snapscore-Botter#14]
How do i fix this? 
![image](https://user-images.githubusercontent.com/103876681/164949246-e3167f1a-c282-477d-a144-ca990effb9c3.png)

**Comment by pranavpa8788** [comment]
Are you in the same directory as where you cloned it?

**Comment by useragents** [comment]
You are not in the same directory where the `requirements.txt` file is located. Use `cd (path)` to move to the correct directory, or alternatively, you can type the following into Command Prompt:
```
pip install
