### ISSUE TITLE
Installed All Requirements and Still Says I Need To Install Them

### ISSUE THREAD

**Issue by HesBasic** [useragents/Snapchat-Snapscore-Botter#15]
i installed all the requirements needed. Even did more than that by going further to try again multiple times. It says in command prompt all them are already downloaded. Still wont work though.

**Comment by useragents** [comment]
You likely have more than 1 Python version installed and when you installed the modules, they were installed to the wrong Python path.

**Comment by useragents** [comment]
If so, make sure you only have 1 Python installed and then try again. 👍
