### ISSUE TITLE
ERROR: Error [WinError 5] Access is denied while executing command python setup.py egg_info error

### ISSUE THREAD

**Issue by Ulcerousturnip** [useragents/Snapchat-Snapscore-Botter#16]
I don't know what this is or how to fix it, happens when i try to install requirements.txt and PyAutoGUI==0.9.53. I am already running cmd as admin

C:\Windows\system32>pip install pyautogui
Collecting pyautogui
  Using cached PyAutoGUI-0.9.53.tar.gz (59 kB)
  Preparing metadata (setup.py) ...   ERROR: Error [WinError 5] Access is denied while executing command python setup.py egg_info
error
ERROR: Could not install packages due to an OSError: [WinError 5] Access is denied
Check the permissions.

**Comment by useragents** [comment]
This is unrelated to my script as this is an issue on your end. I will try and help; run Command Prompt as Administrator and try again. If this does not work, a quick google search will help you.

**Comment by maslouts** [comment]
![image](https://user-images.githubusercontent.com/70969979/191158302-2355a219-6889-4c07-a525-5276a0259ec0.png)
Linux上装报错怎么解决求解，谢谢
