### ISSUE TITLE
requirements.txt

### ISSUE THREAD

**Issue by IcedTea60** [useragents/Snapchat-Snapscore-Botter#18]
hey i was wondering something, i had a problem when i tried to use the command u used "pip install -r requirements.txt" when i had done this it gave me an error saying "ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'" do you know what this is and how i can fix it?

**Comment by useragents** [comment]
This issue is not related to my script so this has been closed, but this has already been answered [here](https://github.com/useragents/Snapchat-Snapscore-Botter/issues/14#issuecomment-1107857757).
