### ISSUE TITLE
ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'

### ISSUE THREAD

**Issue by neko5star** [useragents/Snapchat-Snapscore-Botter#20]
ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'
tried to instal requierments,txt in cmd didn"t work
![Screenshot (7)](https://user-images.githubusercontent.com/80632782/166672083-d157e5d2-ae22-44b5-b719-cc96a3f92832.png)

**Comment by Marciano0** [comment]
i am having the same issue, you got a fix?

**Comment by maxsteinwand** [comment]
You have to switch to the extraced folder path. Example:

cd C:\Users\<yourusername>\Downloads\Snapchat-Snapscore-Botter-main

then you can run "pip install -r requirements.txt"

**Comment by useragents** [comment]
Thanks to @maxsteinwand this has been answered.
