### ISSUE TITLE
not working 

### ISSUE THREAD

**Issue by neko5star** [useragents/Snapchat-Snapscore-Botter#21]
the program stoped working

**Comment by useragents** [comment]
Any specific error?

**Comment by ksyp-7** [comment]
its too fast,
it is not waiting for capturing snap,
so before snap is taken it moves to spotlight section rather than it should wait for capturing snap and than after move to send section....

**Comment by demonlol** [comment]
@ksyp-7 If you're still having issues, you can adjust how long the program sleeps to compensate for your emulator's performance.

**Comment by useragents** [comment]
I have updated the [main.py](https://github.com/useragents/Snapchat-Snapscore-Botter/blob/main/main.py) script to have a configuration of speeds (fast/slow PC). You can download the latest version [here](https://github.com/useragents/Snapchat-Snapscore-Botter/archive/refs/heads/main.zip).
