### ISSUE TITLE
No Shortcuts

### ISSUE THREAD

**Issue by x198x** [useragents/Snapchat-Snapscore-Botter#23]
There is the shortcuts on my phone but not on pc

**Comment by demonlol** [comment]
Possibly a os or resolution/dpi related issue. Because everyone should have the same version of the app...right?

**Comment by useragents** [comment]
I'm not sure why this may occur, there are shortcuts for me. This may be due to the app version, android version, or others. It
It could also possibly be what @demonlol said.
