### ISSUE TITLE
main closing instantly

### ISSUE THREAD

**Issue by thonboGamer** [useragents/Snapchat-Snapscore-Botter#7]
![image](https://user-images.githubusercontent.com/89350427/163503308-a1b3a9c5-23c3-4ff4-9176-8ef1b50bf997.png)

**Comment by useragents** [comment]
If you are not in the correct directory, please move to the correct one using `cd (directory)` where the requirements.txt file is located. Or, you can type `pip install requests` in Command Prompt. 👍
