### ISSUE TITLE
Snapchat was unable to open the camera. You may need to restart the application or your device.

### ISSUE THREAD

**Issue by thonboGamer** [useragents/Snapchat-Snapscore-Botter#8]
![image](https://user-images.githubusercontent.com/89350427/163581801-de5d7e12-f9d5-4f22-9679-779413ce27cd.png)

ive restarted n everything and it dosent work on blue stacks either

**Comment by 8ua** [comment]
What are emulator ?

**Comment by 8ua** [comment]
What emulator?

**Comment by thonboGamer** [comment]
nox

**Comment by 8ua** [comment]
> 

try use memu

**Comment by useragents** [comment]
NoxPlayer should work fine. Are you sure you have your camera setup properly?

**Comment by thonboGamer** [comment]
memu wont start for me

**Comment by useragents** [comment]
I am not sure what the issue is, you may not have a camera or something. If you don't have a camera, you can get a virtual camera. Check this YouTube tutorial [here](https://www.youtube.com/watch?v=r1OcXiXdw7U) on how to get an OBS virtual camera.
