### ISSUE TITLE
I dont have the arrow and multi snap

### ISSUE THREAD

**Issue by 94q** [useragents/Snapchat-Snapscore-Botter#9]
![image](https://user-images.githubusercontent.com/80714938/163708509-a1695078-2f37-48e5-8aeb-8ba237528b6b.png)

What version of blue stacks do you have and what snapchat version is it?

I have the newest versions of both.

**Comment by useragents** [comment]
I use the latest NoxPlayer with the latest version of Snapchat. I'm not sure why the arrow doesn't appear, are you sure you have your camera setup?

**Comment by useragents** [comment]
Closed due to inactivity. Likely the camera was not setup properly 👍
